### ISSUE TITLE
Error building html with subfolder

### ISSUE THREAD

**Issue by CesarDenis** [carlosl/gulp-nunjucks-render#38]
In my project I need the following file structure:

```
webapp
└── app
    ├── index.html
    ├── subfolder
    │   ├── index.html
    ├── includes
    │   ├── footer.html
    │   └── header.html
    └── layouts
        └── default.html
```

When I build the HTML, the following error occurs:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Error: File not found with singular glob: /Users/macweb01/Sites/ccr/ras/styles/main.css
    at DestroyableTransform.<anonymous> (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/lib/streamManager.js:90:36)
    at emitOne (events.js:95:20)
    at DestroyableTransform.emit (events.js:182:7)
    at emitOne (events.js:90:13)
    at DestroyableTransform.emit (events.js:182:7)
    at Glob.<anonymous> (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/index.js:38:16)
    at Glob.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Glob.emit (events.js:182:7)
    at Glob._finish (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/Users/macweb01/Sites/ccr/ras/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
    at RES (/Users/macweb01/Sites/ccr/ras/node_modules/inflight/inflight.js:23:14)
```

My `html` task:
```js
gulp.task('html', ['views', 'styles', 'scripts'], () => {
  return gulp.src([
      'app/**/*.html',
      '.tmp/**/*.html',
      '!.tmp/includes/**/*.html',
      '!.tmp/layouts/**/*.html',
      '!app/includes/**/*.html',
      '!app/layouts/**/*.html'
    ])
    .pipe($.useref({searchPath: ['.tmp', 'app', '.']}))
    .pipe($.if('*.js', $.uglify()))
    .pipe($.if('*.css', $.cssnano()))
    .pipe($.if('*.js', $.rev()))
    .pipe($.if('*.css', $.rev()))
    .pipe($.revReplace())
    .pipe($.if('*.html', $.htmlmin({collapseWhitespace: true})))
    .pipe(gulp.dest('dist'));
});
```

And my `view` task:
```js
gulp.task('views', () => {
  return gulp.src('app/**/*.html')
    .pipe($.nunjucksRender({
      path: ['app/']
    }))
    .pipe(gulp.dest('.tmp'))
});
```

Can someone help me?
Thanks.

**Comment by kamlekar** [comment]
Not sure.. Just guessing..

Why `$.nunjucksRender`?

**Comment by CesarDenis** [comment]
I'm use the [generator-webapp](https://github.com/yeoman/generator-webapp), and they use the `gulp-load-plugins` to load plugins:

```js
import gulpLoadPlugins from 'gulp-load-plugins';
const $ = gulpLoadPlugins();
```

**Comment by kristijanhusak** [comment]
According to the error stack trace, it's problem with useref, not nunjucksRender. Try running task without useref and see what happens.

**Comment by CesarDenis** [comment]
Thanks @kristijanhusak  , the problem is in the configuration of the `useref`
